name: herrcomp
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - scipy
  - seaborn
  - jupyter
  - notebook==6.4.0
#  - notebook==5.7.10
 # - superlu_dist=6.2.0
  - rise
  - jupyterlab-lsp
  - python-lsp-server
  - ipywidgets
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - pandas
#  - pulp
#  - bokeh
#  - ipyvolume
#  - plotly
  - vpython
  - jupyterlab-vpython
#  - fenics
#  - mshr
#  - nbtutor
  - pip
  - pip:
    - nbgrader
    - tutormagic
#    - notebook==6.4.0
